### ISSUE TITLE
Can't install on a new (latest) version of clearOS

### ISSUE THREAD

**Issue by godbout** [WikiSuite/app-lets-encrypt#14]
Hi there!

I'm trying to install a couple of WikiSuite components including the lets-encrypt one but I keep having the following error:

````
Error: Package: 1:app-certificate-manager-2.4.20-1.v7.noarch (clearos-verified)
           Requires: app-certificate-manager-core = 1:2.4.20-1.v7
           Installed: 1:app-certificate-manager-core-2.4.21-1.v7.noarch (@clearos-updates)
               app-certificate-manager-core = 1:2.4.21-1.v7
           Available: 1:app-certificate-manager-core-2.4.5-1.v7.noarch (clearos)
               app-certificate-manager-core = 1:2.4.5-1.v7
           Available: 1:app-certificate-manager-core-2.4.20-1.v7.noarch (clearos-verified)
               app-certificate-manager-core = 1:2.4.20-1.v7
````

Seems there's a compatibility issue?

**Comment by benoitg** [comment]
@godbout I just successfully installed it.  It seems you were unlucky enough to try to install at the exact moment  app-certificate-manager 2.4.21 was getting into the repository.  Can you try again?

**Comment by pcbaldwin** [comment]
Ugh... caught by this again.  I just pushed the most recent version of the Certificate Manager (2.4.21) to the verified repositories, so you should be all set.  This was scheduled for release in a couple of hours from now, so no big deal.

Long version: there's a feature in ClearOS Community that lets end users upgrade to the Business edition in the first 30 days.  Here's what happened:

- A bleeding edge version of the Certificate Manager **API** from the regular software repositories (v2.4.20 in clearos-updates) was installed.  This was done via the command line, via an install script of some kind, by leaving a fresh install on overnight which then auto-updated, or, some other way.

- The ClearOS system was then registered and the regular Community software repositories (clearos-updates) were disabled and the Business software repositories (clearos-verified) were enabled.

- When you tried to install Let's Encrypt, the installer also requested the Certificate Manager **UI** (the related API was already installed).  The Certificate Manager API is the bleeding edge 2.4.21, but that UI in the in the Business Edition software repositories was still 2.4.20.   Result: version mismatch... bad.

I have opened up a tracker item with ClearOS to see if we can get this 30-day window - https://tracker.clearos.com/view.php?id=19811   It's certainly a good idea, but in practice it's not practical and quite problematic.

**Comment by godbout** [comment]
Working now. Excellent. Thank you both, and thanks @pcbaldwin for the great explanation. Just trying things out for now, let's see if I can help later :)
