### ISSUE TITLE
Requesting certificate takes for ever

### ISSUE THREAD

**Issue by techana** [WikiSuite/app-lets-encrypt#4]
Adding a certificate through the app (ver. 1.0.7-1 on ClearOS 7.4) does not seem to work. It gives this message: Requesting certificate... and keep spinning for ever!

There is a note in the installation page says:
> If it doesn't take effect right away,
> just use another browser (ex.: Firefox instead of Chrome)

I switched to Firefox and still the same problem, no certificate was generated.

Thank you.

**Comment by techana** [comment]
It turned out that my domain was not accessible from the internet. I fixed the issue with the domain registrar, and then was able to generate a certificate using the Let's Encrypt app in clearOS.

One note though that the app never gave me a success message and just kept spinning "Requesting certificate..."! I tailed the log and found the following:

> /etc/letsencrypt/live/xxxxx.com/privkey.pem
> Your cert will expire on 2018-03-13. To obtain a new or tweaked version of this certificate in the future, simply run certbot again. To non-interactively renew *all* of your certificates, run "certbot renew"
> 2017-12-13 04:20:34,467:DEBUG:certbot.reporter:Reporting to user: If you like Certbot, please consider supporting our work by:
> 
> Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
> Donating to EFF:                    https://eff.org/donate-le

I knew then that it had been successfully completed. I retuned to the main page and found the certificate there.

As a feature request, it would be better to add a feature informing the user about the progress of the operation.

Thank you.

**Comment by pcbaldwin** [comment]
FYI - there was a stray debug statement that was causing grief:
https://github.com/WikiSuite/app-lets-encrypt/commit/d3db4409ae3008ce823784987e578eb5bf501aab

Note: this only impacted the version in the testing repos (1.07).  The production release (1.06) is still okay.
