### ISSUE TITLE
Feature Request: add option to select the log retention

### ISSUE THREAD

**Issue by NickJH** [WikiSuite/app-lets-encrypt#7]
By default, certbot keeps 1000 log files. At one a day this is nearly 3 years of daily logs. In certbot there is a configurable option, --max-log-backups, which can be used to specify how many logs to keep. Can this be exposed in the app-lets-encrypt interface, or as a halfway house, have a file like /etc/sysconfig/certbot and have a commented out OPTIONS="" line which can be hand edited with the options required (e.g. "max-log-backups 200") and have this file read as part of the cron job//usr/clearos/apps/lets_encrypt/deploy/renew where you could add:

if [ -f /etc/sysconfig/certbot ];then 
	. /etc/sysconfig/certbot
fi

and change the line:

RESULT=`certbot renew --preferred-challenges http-01 --renew-hook "/sbin/trigger lets_encrypt" >/var/clearos/lets_encrypt/renew.log 2>&1`

to

RESULT=`certbot renew --preferred-challenges http-01 $OPTIONS --renew-hook "/sbin/trigger lets_encrypt" >/var/clearos/lets_encrypt/renew.log 2>&1`

in the style of the old init functions

**Comment by pcbaldwin** [comment]
Strange.  The --max-log-backups doesn't seem to prune older files.  For example, I have 210 renewal logs but setting "--max-log-backups 200" doesn't prune the logs back down to 200.  The log rotation does get set to 200, but log files 201-210 are orphaned.

I have set the default for the ClearOS renewal script to 200.  The MAX_LOGS parameter in /etc/sysconfig/certbot can be used to override this default, e.g.: MAX_LOGS=1000

**Comment by NickJH** [comment]
I've seen that as well and at some point I will try to file a bug - one more account to open!
Thanks for the update.

One thing which may break it is that when you request a new certificate, it does not get requested with the --max-log-backups set so creates an extra file. Presumably this also goes for deletion. Every certbot action creates a log file, but still when certbot bumps into --max-log-backups I would have thought it should prune all files > --max-log-backups.
